CREATE TABLE CHEF (
    CHEF_ID BIGSERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    EMAIL_ADDRESS VARCHAR(64) NOT NULL UNIQUE,
    CHEF_PASSWORD VARCHAR(64) NOT NULL
);

CREATE TABLE RECIPE(
    RECIPE_ID BIGSERIAL PRIMARY KEY,
    RECIPE_NAME VARCHAR(64) NOT NULL UNIQUE,
    CATEGORY VARCHAR(16) NOT NULL,
    INGREDIENTS VARCHAR(100) NOT NULL,
    INSTRUCTIONS TEXT NOT NULL,
    CREATOR_ID BIGINT NOT NULL
);
ALTER TABLE RECIPE ADD FOREIGN KEY (CREATOR_ID) REFERENCES CHEF(CHEF_ID);


CREATE TABLE MEAL_PLAN(
    MEAL_PLAN_ID BIGSERIAL PRIMARY KEY,
    RECIPE_ID BIGINT NOT NULL,
    CHEF_ID BIGINT NOT NULL,
    MEAL_PLAN_DATE DATE
);
ALTER TABLE MEAL_PLAN ADD FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID);
ALTER TABLE MEAL_PLAN ADD FOREIGN KEY (CHEF_ID) REFERENCES CHEF(CHEF_ID);
CREATE INDEX IDX_MEAL_PLAN_DATE_ ON MEAL_PLAN(MEAL_PLAN_DATE);


CREATE TABLE CHEF_RECIPE(
    CHEF_RECIPE_ID BIGSERIAL PRIMARY KEY,
    RECIPE_ID BIGINT NOT NULL,
    CHEF_ID BIGINT NOT NULL
);
ALTER TABLE CHEF_RECIPE ADD FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID);
ALTER TABLE CHEF_RECIPE ADD FOREIGN KEY (CHEF_ID) REFERENCES CHEF(CHEF_ID);
