CREATE TABLE CHEF (
    CHEF_ID BIGSERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    EMAIL_ADDRESS VARCHAR(64) NOT NULL UNIQUE,
    CHEF_PASSWORD VARCHAR(64) NOT NULL,
    DELETED BIT DEFAULT 0
);

CREATE TABLE RECIPE(
    RECIPE_ID BIGSERIAL PRIMARY KEY,
    RECIPE_NAME VARCHAR(64) NOT NULL UNIQUE,
    CATEGORY VARCHAR(16) NOT NULL,
    INSTRUCTIONS TEXT NOT NULL,
    CREATOR_ID BIGINT NOT NULL,
    DELETED BIT DEFAULT 0
);
ALTER TABLE RECIPE ADD FOREIGN KEY (CREATOR_ID) REFERENCES CHEF(CHEF_ID);


CREATE TABLE MEAL_PLAN(
    MEAL_PLAN_ID BIGSERIAL PRIMARY KEY,
    RECIPE_ID BIGINT NOT NULL,
    CHEF_ID BIGINT NOT NULL,
    MEAL_PLAN_DATE DATE,
    DELETED BIT DEFAULT 0
);
ALTER TABLE MEAL_PLAN ADD FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID);
ALTER TABLE MEAL_PLAN ADD FOREIGN KEY (CHEF_ID) REFERENCES CHEF(CHEF_ID);
CREATE INDEX IDX_MEAL_PLAN_DATE_ ON MEAL_PLAN(MEAL_PLAN_DATE);


CREATE TABLE FAVORITE(
    FAVORITE_ID BIGSERIAL PRIMARY KEY,
    RECIPE_ID BIGINT NOT NULL,
    CHEF_ID BIGINT NOT NULL,
    DELETED BIT DEFAULT 0
);
ALTER TABLE FAVORITE ADD FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID);
ALTER TABLE FAVORITE ADD FOREIGN KEY (CHEF_ID) REFERENCES CHEF(CHEF_ID);

CREATE TABLE INGREDIENT(
    INGREDIENT_ID BIGSERIAL PRIMARY KEY,
    INGREDIENT_NAME VARCHAR(64) NOT NULL,
    DELETED BIT DEFAULT 0
);

CREATE TABLE RECIPE_HAS_INGREDIENT(
    RECIPE_HAS_INGREDIENT_ID BIGSERIAL PRIMARY KEY,
    RECIPE_ID BIGINT NOT NULL,
    INGREDIENT_ID BIGINT NOT NULL,
    DELETED BIT DEFAULT 0
);
ALTER TABLE RECIPE_HAS_INGREDIENT ADD FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID);
ALTER TABLE RECIPE_HAS_INGREDIENT ADD FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(INGREDIENT_ID);

CREATE TABLE CHEF_INGREDIENT(
    CHEF_INGREDIENT_ID BIGSERIAL PRIMARY KEY,
    CHEF_ID BIGINT NOT NULL,
    INGREDIENT_ID BIGINT NOT NULL,
    DELETED BIT DEFAULT 0
);
ALTER TABLE CHEF_INGREDIENT ADD FOREIGN KEY (CHEF_ID) REFERENCES CHEF(CHEF_ID);
ALTER TABLE CHEF_INGREDIENT ADD FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(INGREDIENT_ID);